dynamic_maic.o : dynamic_main.c ./lib/libstatic.a
	gcc -rdynamic dynamic_main.c -o dynamic_cal_make -ldl
add.o : add.c
	gcc -c ./lib/add.o
subtract.o : subtarct.c
	gcc -c ./lib/subtarct.o
multiply.o : multiply.c
	gcc -c ./lib/multiply.o
divide.o : divide.c
	gcc -c ./lib/divide.o
